version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    command: ["go", "test", "./test/...", "-v"]
    volumes:
      - integration_test_volume:/app
    depends_on:
      - db
  db:
    image: mongo:latest
    env_file:
      - db.env
    volumes:
      - mongo_integration_test_data:/data/db
    ports:
      - "27017:27017"

volumes:
  integration_test_volume:
  mongo_integration_test_data: