version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    command: /bin/sh -c "go build -o ./bin/savingsquadsbackend ./cmd && ./bin/savingsquadsbackend -db-database-name savingsquadsdatabase"
    volumes:
      - data_volume:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: mongo:latest
    env_file:
      - db.env
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  data_volume:
  mongo_data: